name: Phantom
main: art.arcane.phantom.core.PhantomAPIPlugin
version: 1.0.0
authors: [ cyberpwn ]
api-version: 1.19
libraries:
  - com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2
  - org.apache.commons:commons-lang3:3.12.0
  - com.google.code.gson:gson:2.8.9
  - com.elmakers.mine.bukkit:EffectLib:9.4
  - org.bitbucket.mstrobel:procyon-core:0.6.0
  - org.bitbucket.mstrobel:procyon-compilertools:0.6.0
  - org.bitbucket.mstrobel:procyon-reflection:0.6.0
  - org.zeroturnaround:zt-zip:1.15
commands:
  phantom:
    aliases: [ pha ]
